"""Every request-shape limit, once, per docs/architecture/v2-plan.md §F."""

MAX_WORDS_PER_USER = 5000
WORDS_LIST_MAX_LIMIT = 100
WORDS_LIST_DEFAULT_LIMIT = 50
WORDS_BULK_MAX_ROWS = 500
WORD_MAX_LENGTH = 100
DEFINITION_MAX_LENGTH = 500
EXAMPLE_MAX_LENGTH = 250
TRANSLATION_MAX_LENGTH = 200
NOTES_MAX_LENGTH = 1000
DICTIONARY_NAME_MAX_LENGTH = 60
REVIEWS_FORECAST_MAX_DAYS = 60
